### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by mcfadd** [mcfadd/Job_Shop_Schedule_Problem#1]
This issue is for recording a general TODO list of tasks.

### Todo
- [x] Flow diagram describing the steps of our program.
- [x] Create solution class in data_set.py
- [x] Create feasible_solution_factory.py for generating feasible solutions.
- [x] Finish tabu_search.
- [x] Create another instance of the problem (i.e. jobTasks.csv, sequenceDependencyMatrix.csv, machineRunSpeed.csv) that is slightly bigger than the one currently in the [data](https://github.com/mcfadd/Job_Shop_Schedule_Problem/tree/master/data)
- [x] Create a function that generates schedules with start/end times for the job-tasks on each machines given an operation list. (see code TODO comment in Solution class)
- [x] Research how to run multiple TS processes in parallel (i.e. multi-programming) and collect their results when they finish. (see [multi-programming in python](https://realpython.com/python-concurrency/#how-to-speed-up-a-cpu-bound-program))
- [x] Research how/if we can use Cython to speed up runtime (i.e. # iterations of TS performed in a certain duration)

**Comment by chandan-angadi** [comment]
@avaldez96  Could you please explain  seq dep matrix?
